name: git_changie
description: A changelog generator for github.
version: 0.0.7
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  pubspec_yaml: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0


executables:  
  git_changie: git_changie